apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\whitet\Desktop\santesuite\kub-test\mpi\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    package: db
  name: sdb-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      package: db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\whitet\Desktop\santesuite\kub-test\mpi\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        package: db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: SanteDB123
        - name: POSTGRES_USER
          value: santedb
        image: postgres
        imagePullPolicy: ""
        name: sdb-postgres
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
