apiVersion: v1
kind: Service
metadata:
  labels:
    package: db
  name: sdb-postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    package: db
status:
  loadBalancer: {}
