apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    package: santedb
  name: santedb-mpi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      package: santedb
  strategy: {}
  template:
    metadata:
      labels:
        package: santedb
    spec:
      containers:
      - env:
        - name: SDB_DATA_POLICY_ACTION
          value: HIDE
        - name: SDB_DATA_POLICY_RESOURCE
          value: Patient
        - name: SDB_DB_AUDIT
          value: server=sdb-postgres;port=5432; database=auditdb; user id=santedb;
            password=SanteDB123; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;
        - name: SDB_DB_AUDIT_PROVIDER
          value: Npgsql
        - name: SDB_DB_MAIN
          value: server=sdb-postgres;port=5432; database=santedb; user id=santedb;
            password=SanteDB123; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;
        - name: SDB_DB_MAIN_PROVIDER
          value: Npgsql
        - name: SDB_DELAY_START
          value: "5000"
        - name: SDB_FEATURE
          value: LOG;DATA_POLICY;AUDIT_REPO;ADO;PUBSUB_ADO;RAMCACHE;SEC;SWAGGER;OPENID;FHIR;HL7;HDSI;AMI;BIS;MDM;MATCHING
        - name: SDB_MATCHING_MODE
          value: WEIGHTED
        - name: SDB_MDM_AUTO_MERGE
          value: "false"
        - name: SDB_MDM_RESOURCE
          value: Patient=org.santedb.matching.patient.default
        - name: SDB_REDIS_SERVER
          value: sdb-redis:6379
        image: santesuite/santedb-mpi:2.1.3
        imagePullPolicy: ""
        name: santedb-mpi
        ports:
        - containerPort: 8080
        - containerPort: 2100
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
