configMapGenerator:
    - name: santedb-openhim-config-importer-configmap
      files:
        - ./volume/openhim/openhim-import.json
        - ./volume/openhim/openhimConfig.js
  resources:
    - ./core-openhim-config-importer-job.yaml
  