apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: santedb
  name: santedb
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    name: "8080"
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: "2100"
    port: 2100
    targetPort: 2100
  selector:
    io.kompose.service: santedb
status:
  loadBalancer: {}
